name: MacOS
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        include:
          - qt_ver: 5.15.2
            qt_arch: clang_64
            qt_modules: ""
          - qt_ver: 6.6.1
            qt_arch: clang_64
            qt_modules: "qt5compat qtimageformats"
    env:
      qt_target: desktop
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          target: ${{ env.qt_target }}
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          modules: ${{ matrix.qt_modules }}
          cache: 'true'
          cache-key-prefix: 'install-qt-action-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}'
          aqtversion: '==3.0.1'
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
          
      - name: build macos
        run: |
          brew install ninja llvm gsed libomp
          mkdir build
          cd build
          cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ ..
          cmake --build . --parallel --verbose
          cd ..

