name: MacOS
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [5.15.1]
        qt_arch: [clang_64]
    env:
      targetName: Derfla
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
      
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
          
      - name: prepare Sparkle
        run: |
          mkdir -p 3rdparty/Sparkle
          cd 3rdparty/Sparkle
          curl -O -sL https://github.com/sparkle-project/Sparkle/releases/download/1.24.0/Sparkle-1.24.0.tar.xz
          tar Jxvf Sparkle-1.24.0.tar.xz
          cd -

      - name: build macos
        run: |
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ../${{ env.targetName }}.pro
          make -j 2
          cd ..

      - name: package
        run: |
          macdeployqt "bin/x86_64/${targetName}.app" -qmldir=. -verbose=1 -dmg
